import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NextUILayout from "./NextUIProvider";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import { FooterComponent } from "@/components/footer/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}  >
      
        <NextUILayout>
        <NavbarComponent/>
         {children}

         <FooterComponent/>
        </NextUILayout>
        </body>
    </html>
  );
}
